/**
 *
 * Copyright (c) 2022 UPMEM.
 *
 */

#ifndef __SYSTEM_H__
#define __SYSTEM_H__

#include "stm32u5xx_hal.h"
#include "error.h"


#ifdef SYSCLK_160MHZ
#define PWR_REGULATOR_VOLTAGE_SCALE	(PWR_REGULATOR_VOLTAGE_SCALE1)
#define OSC_INIT_OSCILLATORTYPE		(RCC_OSCILLATORTYPE_HSI48|RCC_OSCILLATORTYPE_MSI)
#define OSC_INIT_HSI48STATE		(RCC_HSI48_ON)
#define OSC_INIT_MSISTATE		(RCC_MSI_ON)
#define OSC_INIT_MSICALIBRATION		(RCC_MSICALIBRATION_DEFAULT)
#define OSC_INIT_MSIRANGE		(RCC_MSIRANGE_0)
#define OSC_INIT_PLLSTATE		(RCC_PLL_ON)
#define OSC_INIT_PLLSOURCE		(RCC_PLLSOURCE_MSI)
#define OSC_INIT_PLLMBOOST		(RCC_PLLMBOOST_DIV4)
#define OSC_INIT_PLLM			(3)
#define OSC_INIT_PLLN			(10)
#define OSC_INIT_PLLP			(2)
#define OSC_INIT_PLLQ			(2)
#define OSC_INIT_PLLR			(1)
#define OSC_INIT_PLLRGE			(RCC_PLLVCIRANGE_1)
#define OSC_INIT_PLLFRACN		(0)

#define CLK_INIT_CLOCKTYPE		(RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK \
					|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2 \
					|RCC_CLOCKTYPE_PCLK3)
#define CLK_INIT_SYSCLKSOURCE		(RCC_SYSCLKSOURCE_PLLCLK)
#define CLK_INIT_AHBCLKDIV		(RCC_SYSCLK_DIV1)
#define CLK_INIT_APB1CLKDIV		(RCC_HCLK_DIV1)
#define CLK_INIT_APB2LKDIV		(RCC_HCLK_DIV1)
#define CLK_INIT_APB3LKDIV		(RCC_HCLK_DIV1)

#define FLASH_LATENCY			(FLASH_LATENCY_4)

#elif defined(SYSCLK_80MHZ)

#define PWR_REGULATOR_VOLTAGE_SCALE	(PWR_REGULATOR_VOLTAGE_SCALE2)
#define OSC_INIT_OSCILLATORTYPE		(RCC_OSCILLATORTYPE_HSI48|RCC_OSCILLATORTYPE_MSI)
#define OSC_INIT_HSI48STATE		(RCC_HSI48_ON)
#define OSC_INIT_MSISTATE		(RCC_MSI_ON)
#define OSC_INIT_MSICALIBRATION		(RCC_MSICALIBRATION_DEFAULT)
#define OSC_INIT_MSIRANGE		(RCC_MSIRANGE_0)
#define OSC_INIT_PLLSTATE		(RCC_PLL_ON)
#define OSC_INIT_PLLSOURCE		(RCC_PLLSOURCE_MSI)
#define OSC_INIT_PLLMBOOST		(RCC_PLLMBOOST_DIV4)
#define OSC_INIT_PLLM			(3)
#define OSC_INIT_PLLN			(10)
#define OSC_INIT_PLLP			(2)
#define OSC_INIT_PLLQ			(2)
#define OSC_INIT_PLLR			(2)
#define OSC_INIT_PLLRGE			(RCC_PLLVCIRANGE_1)
#define OSC_INIT_PLLFRACN		(0)

#define CLK_INIT_CLOCKTYPE		(RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK \
					|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2 \
					|RCC_CLOCKTYPE_PCLK3)
#define CLK_INIT_SYSCLKSOURCE		(RCC_SYSCLKSOURCE_PLLCLK)
#define CLK_INIT_AHBCLKDIV		(RCC_SYSCLK_DIV1)
#define CLK_INIT_APB1CLKDIV		(RCC_HCLK_DIV1)
#define CLK_INIT_APB2LKDIV		(RCC_HCLK_DIV1)
#define CLK_INIT_APB3LKDIV		(RCC_HCLK_DIV1)

#define FLASH_LATENCY			(FLASH_LATENCY_2)

#else
#error "At least SYSCLK_160MHZ or SYSCLK_80MHZ must be defined"
#endif

void SystemClock_Config(void);
void SystemPower_Config(void);
pilot_error_t check_timeout (uint32_t timestamp, uint32_t timeout);
inline uint32_t get_timestamp(void){
  return HAL_GetTick();
}
#endif
